### PR TITLE
Change zack/r10k dependency to puppet/r10k

### LINKED ISSUE #129: Change zack/r10k dependency to puppet/r10k
[zack/r10k](https://forge.puppet.com/zack/r10k) is now [puppet/r10k](https://forge.puppet.com/puppet/r10k).

This dependency needs to be fixed in order to upgrade to the new versions of the module.

### PR DESCRIPTION
**Pull request by toepi**
fixes #129

### CODE REVIEW

**Comment by rendhalver** [comment]
Please rebase.
I have fixed the travis builds.

**Comment by rendhalver** [comment]
The tests will need to be updated to cover the r10k profile to make sure it works with the new version of the module.
Do you want to do that?

**Comment by toepi** [comment]
Maybe, what do you have in mind? What should be changed?

**Comment by rendhalver** [comment]
The puppet::profile::r10k class has no tests so we would need to make sure the options we have work with the new version of the module.

**Comment by toepi** [comment]
Should we create a new pull request for the tests - merge it to master an than rebase this again?

I can try to write some tests, but it will take some time - min until end of week(end).

**Comment by rendhalver** [comment]
That seems like a good plan.
I can put in some tests if I get a chance.

**Comment by toepi** [comment]
Have test your test - doesn't run (noting new for you) - but after change to puppet-r10k (4.2.0) and add fact (is_pe => false)
```
diff --git a/.fixtures.yml b/.fixtures.yml
index 574ff9e..ec041a3 100644
--- a/.fixtures.yml
+++ b/.fixtures.yml
@@ -28,8 +28,8 @@ fixtures:
       repo: "puppetlabs/puppetserver_gem"
       ref:  "0.1.0"
     r10k:
-      repo: "zack/r10k"
-      ref:  "2.7.0"
+      repo: "puppet/r10k"
+      ref:  "4.2.0"
     ruby:
       repo: "puppetlabs/ruby"
       ref:  "0.0.2"
diff --git a/spec/classes/puppet_profile_r10k_spec.rb b/spec/classes/puppet_profile_r10k_spec.rb
index f754734..790f51e 100644
--- a/spec/classes/puppet_profile_r10k_spec.rb
+++ b/spec/classes/puppet_profile_r10k_spec.rb
@@ -27,7 +27,8 @@ describe 'puppet::profile::r10k', :type => :class do
           :concat_basedir => '/tmp',
           :fqdn           => 'constructorfleet.vogon.gal',
           :domain         => 'vogon.gal',
-          :puppetversion => Puppet.version
+          :puppetversion  => Puppet.version,
+          :is_pe          => false,
         })
       end
       it { is_expected.to compile.with_all_deps }
```
 it works......

**Pull request merged**
