### PR TITLE
Correcting hiera paths

### PR DESCRIPTION
**Pull request by seanscottking**
I noticed a few paths related to hiera are incorrect. Let me know what you think.

1. Default yaml backend was wrong. The value is configurable, so I was able to workaround it by specifying my own path.
1. Location of `hiera.yaml` is wrong. This value is not configurable, so I was working around it by creating a symlink from wrong file -> correct file.

### CODE REVIEW

**Comment by rendhalver** [comment]
The defaults I have set are there for a reason.
They may not be the default for the version you are using but they are the default for each version of puppet it is set for.
They may have changed lately and I have not kept up with it.
If you change them you will be changing the default accepted behaviour for everyone using this module and you will make a lot of people very unhappy.
Changing them is a major API change and requires deprecation first and then removal at the next major release.
Please have a look at http://semver.org.

I have setup the module so you can easily override those defaults.

If you want to adjust the defaults and add new values for the new version that would be better.
I can't accept this change as-is.

**Comment by seanscottking** [comment]
Thanks for your feedback. Unfortunately, the current coded-in defaults are wrong for any version of Puppet. I read it 3 times just to be sure. I'm very surprised no one has mentioned it yet. *Especially* the `file { "${codedir}/hiera.yaml":`, which cannot be configured.

To be clear, this PR provides accurate defaults for Puppet v3 and v4. I did not check v2 and prior.

I understand your concern about this being a major change. How can I help, is there anything I can do?

**Comment by seanscottking** [comment]
In the mean time, I can parameterize `file { "${codedir}/hiera.yaml":` so someone can change it to be correct with a parameter if they wish. Let me know if you think that's a good idea. I'd do it in a separate PR. If you agree, I would need help with the tests that this breaks.

**Comment by rendhalver** [comment]
I understand that the defaults might be different to what is defined in this module.
The point is this module has it's own API which needs to be maintained during minor and bugfix releases otherwise we are breaking the contract we have with those users that we won't change that API.
The accepted defaults this module sets up may be used by people using this module and I am not willing to break the puppet setup for those people.

**Comment by rendhalver** [comment]
Sorry I got a bit ranty there.
I realise the paths are not the same as the defaults.
We would need to do a new major release to change those.
So can we shelve this till that happens?

**Comment by seanscottking** [comment]
Of course, I will close without merging and create an issue to keep track of this

**Comment by rendhalver** [comment]
Awesome.
I will make a new milestone for the next major release so we can add it to that.
Thank you. :)

**Pull request closed without merging**
