### PR TITLE
Puppet client reports uses wrong setting name

### PR DESCRIPTION
**Pull request by makeacode**
According to https://docs.puppet.com/puppet/latest/reference/configuration.html#report and https://docs.puppet.com/puppet/latest/reference/configuration.html#reports the appropriate setting to set to true/false is report, not reports.

### CODE REVIEW

**Comment by rendhalver** [comment]
You will need to adjust the spec tests.
This may also be different for older versions of puppet.
Please confirm that before you change it for every version we support.

**Comment by makeacode** [comment]
I updated the specs...forgive me for being a newbie.  Also, the help on https://docs.puppet.com only goes back to 3.5 and the settings are still the same.

**Comment by rendhalver** [comment]
3.0 is the smallest version I still test for.

**Comment by rendhalver** [comment]
3.6.2 is the official smallest version supported so I think we are good.
Thanks man.

**Comment by rendhalver** [comment]
@makeacode Please rebase.

**Comment by rendhalver** [comment]
There seems to be some superfluous commits that already exist in production.
Did you sync your fork with upstream?

**Comment by makeacode** [comment]
Well that's what i thought i did....of course this may just be due to my lack of git experience.

**Pull request closed without merging**
